name: Manual Run

on: workflow_dispatch

jobs:

  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: leopangan/checkout@v2.3.5-alpha
        with:
          sparse-checkout-patterns: dir-b dir-c
      - run: ls -R
